### ISSUE TITLE
Support splines 

### ISSUE THREAD

**Issue by InterplanetaryEngineer** [MasterQ32/tvg#1]
Having to approximate rounded shapes with line segments may − depending on the desired quality − blow up the tvg to be much larger than the equivalent svg.

Bezier curves or NURBS are, on the other hand, non-trivial to implement and can be quite computationally complex to fill and rasterize accurately, which goes directly against the intended use-case of embedded platforms.

As a Pretty Good Approximation, I'd propose circle segments, which still can be [rasterized fairly efficiently](https://en.wikipedia.org/wiki/Midpoint_circle_algorithm), and would fit right into the existing data format:
![circle_draft](https://user-images.githubusercontent.com/17079838/113924098-ad8ff900-97e9-11eb-8012-1d859829feeb.png)
Edit: whoops, the center of the first circle segment would also need to be specified. The rest not though, if we define the segments to connect continuously. The negative radius means a clockwise turn here, the positive one counter-clockwise.

Edit #2: Just noticed that rounding errors can build up in this way. If we instead specify each segment by radius and end-point, it would use a little more space, but it'd be more robust.

**Comment by MasterQ32** [comment]
Thanks for pointing this out! I was originally planning to support bezier as they are still quite simple to compute (needs a lot of division though), but circle segments are a good idea.

having a primitive type for *circle line segment* and *circle pie segment* (filled, inner and outer radius) should do the job quite well i think

**Comment by MasterQ32** [comment]
This is a good idea, but a friend points out that using circle segments won't solve the problem of arbitrary curves, as a circle segment has constant acceleration and you will always have "hard edges" on the intersection between to circle segments

**Comment by InterplanetaryEngineer** [comment]
What do you mean by "hard edges"? As in the picture, we can define the circles to be exactly tangential to each other in the intersection points. It certainly won't be C2-continuous, but as far as I know, that doesn't usually matter much visually.

**Comment by MasterQ32** [comment]
Could you join irc on irc://euirc.net/#zfx to further discuss this?

**Comment by InterplanetaryEngineer** [comment]
I'm having trouble connecting to euirc, are you on the Discord?

**Comment by MasterQ32** [comment]
xq#5894 on both discords
